In [ ]:
# numpy

import numpy as np

In [ ]:
array = np.array([1,5,6,2,3]) # create 1 d array

print(array)

array3 = np.array([[1,2,3],[8,7,9]])

print(array3)

[1 5 6 2 3]
[[1 2 3]
 [8 7 9]]


In [ ]:
# array creation function

zeroes = np.zeros((2,2))

print(zeroes)

ones = np.ones((3,5))

print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

print(ones)

arrange = np.arange(0,10,2)

print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

print(arrange)

linspace = np.linspace(0,10,5)

print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

print(linspace)

print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

random = np.random.rand(3,4)

print(random)

[[0. 0.]
 [0. 0.]]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[0 2 4 6 8]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[ 0.   2.5  5.   7.5 10. ]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[[0.60054996 0.44591263 0.22897648 0.16849733]
 [0.98959552 0.35754676 0.01631191 0.4578524 ]
 [0.03061275 0.53326684 0.35434156 0.08429751]]


In [ ]:
# array attribututes

array = np.array([[1,3,7],[7,9,5],[6,4,2]])

print(array)

print(array.shape)

print(array.size)

print(array.ndim)

[[1 3 7]
 [7 9 5]
 [6 4 2]]
(3, 3)
9
2


In [ ]:
# array indexing and slicing

array = np.array([1,3,4,5,2])

print(array[2:4])

print(array[:])



[4 5]
[1 3 4 5 2]


In [ ]:
# array operation

array1 = np.array([1,3,4,5,2])
array2 = np.array([1,3,4,5,2])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 % array2)
print(array1 ** array2)

print(np.sum(array1))
print(np.min(array1))
print(np.max(array1))
print(np.mean(array1))

[ 2  6  8 10  4]
[0 0 0 0 0]
[ 1  9 16 25  4]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[   1   27  256 3125    4]
15
1
5
3.0


In [ ]:
# Matrix Operations

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A.dot(B))       # Matrix multiplication
print(np.transpose(A)) # Transpose

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
# array reshape

n = np.linspace(0,10,6)

print(n)

update = n.reshape(2,3)

print(update)


[ 0.  2.  4.  6.  8. 10.]
[[ 0.  2.  4.]
 [ 6.  8. 10.]]
